language: node_js

node_js :
    - "v4.2.1"
    - "v5"

addons:
    postgresql: "9.4"


services:
  - mysql
  - postgresql


before_script:
  - psql -f test/sql/createdb.sql -U postgres
  - psql -f test/sql/postgres.sql -U postgres
  - mysql -e 'create database ee_orm_test_mysql;'


sudo: false
