language: node_js

node_js :
    - "0.12"
    - "iojs"

addons:
    postgresql: "9.4"

before_script:
  - psql -f test/createdb.sql -U postgres
  - psql -f test/postgres.sql -U postgres
  - mysql -e 'create database ee_orm_test_mysql;'
